#localization

class Loc:
    # Текущий язык по умолчанию
    lang = "en" 
    
    # Список доступных языков для меню
    lang_names = {
        "en": "English",
        "ru": "Русский",
        "kk": "Қазақша",
        "ky": "Кыргызча",
        "uz": "O'zbekcha",
        "tt": "Татарча",
        "az": "Azərbaycan",
        "tr": "Türkçe",
        "uk": "Українська",
        "pl": "Polski",
        "cs": "Čeština",
        "es": "Español",
        "fr": "Français",
        "de": "Deutsch",
        "it": "Italiano",
        "pt": "Português",
        "nl": "Nederlands",
        "ko": "한국어",
        "ar": "العربية",
        "ja": "日本語",
        "zh": "中文"
    }

    data = {
        "en": {
            "title_default": "TO-DO",
            "new_task_hint": "+ New task",
            "menu_new_note": "📝 New Note",
            "menu_rename": "✏️ Rename Current",
            "menu_archive": "🗑 Archive Manager",
            "menu_language": "🌐 Language",
            "menu_go_to": "🗂 Go to Note",
            "menu_empty": "(Empty)",
            "menu_exit": "Exit",
            "ctx_delete": "Delete",
            "ctx_subtask": "Add Subtask",
            "ctx_cancel": "Cancel / Skip",
            "ctx_restore": "Restore",
            "archive_title": "ARCHIVE MANAGER",
            "btn_open": "Open",
            "btn_delete": "Delete",
            "btn_close": "Close",
            "hint_double_click": "Double-click to open",
            "msg_del_title": "Delete",
            "msg_del_text": "Delete this note permanently?",
            "note_prefix": "Note from",
            "note_to": "to",
            "done_by": "done by",
            "rename_title": "Rename",
            "rename_label": "Note name:",
            # --- Новые ключи ---
            "current_note": "Current Note",
            "delete_confirm_title": "Delete Note?",
            "delete_confirm_text": "Delete this note forever?"
        },
        "ru": {
            "title_default": "ЗАДАЧИ",
            "new_task_hint": "+ Новая задача",
            "menu_new_note": "📝 Новая заметка",
            "menu_rename": "✏️ Переименовать",
            "menu_archive": "🗑 Архив",
            "menu_language": "🌐 Язык",
            "menu_go_to": "🗂 Перейти к заметке",
            "menu_empty": "(Пусто)",
            "menu_exit": "Выход",
            "ctx_delete": "Удалить",
            "ctx_subtask": "Добавить подпункт",
            "ctx_cancel": "Отменить / Пропустить",
            "ctx_restore": "Восстановить",
            "archive_title": "УПРАВЛЕНИЕ АРХИВОМ",
            "btn_open": "Открыть",
            "btn_delete": "Удалить",
            "btn_close": "Закрыть",
            "hint_double_click": "Дважды кликните, чтобы открыть",
            "msg_del_title": "Удаление",
            "msg_del_text": "Удалить эту заметку навсегда?",
            "note_prefix": "Заметка от",
            "note_to": "до",
            "done_by": "сделано",
            "rename_title": "Переименовать",
            "rename_label": "Название заметки:",
            # --- Новые ключи ---
            "current_note": "текущую заметку",
            "delete_confirm_title": "Удалить заметку?",
            "delete_confirm_text": "Вы точно хотите удалить эту заметку навсегда?"
        },
        "kk": {
            "title_default": "ТАПСЫРМАЛАР",
            "new_task_hint": "+ Жаңа тапсырма",
            "menu_new_note": "📝 Жаңа жазба",
            "menu_rename": "✏️ Атын өзгерту",
            "menu_archive": "🗑 Мұрағат",
            "menu_language": "🌐 Тіл",
            "menu_go_to": "🗂 Жазбаға өту",
            "menu_empty": "(Бос)",
            "menu_exit": "Шығу",
            "ctx_delete": "Жою",
            "ctx_subtask": "Ішкі тапсырма қосу",
            "ctx_cancel": "Болдырмау / Өткізу",
            "ctx_restore": "Қалпына келтіру",
            "archive_title": "МҰРАҒАТТЫ БАСҚАРУ",
            "btn_open": "Ашу",
            "btn_delete": "Жою",
            "btn_close": "Жабу",
            "hint_double_click": "Ашу үшін екі рет басыңыз",
            "msg_del_title": "Жою",
            "msg_del_text": "Бұл жазбаны біржолата жою керек пе?",
            "note_prefix": "Жазба уақыты:",
            "note_to": "-",
            "done_by": "орындалды",
            "rename_title": "Атын өзгерту",
            "rename_label": "Жазба атауы:"
        },
        "ky": {
            "title_default": "МИЛДЕТТЕР",
            "new_task_hint": "+ Жаңы милдет",
            "menu_new_note": "📝 Жаңы жазуу",
            "menu_rename": "✏️ Атын өзгөртүү",
            "menu_archive": "🗑 Архив",
            "menu_language": "🌐 Тил",
            "menu_go_to": "🗂 Жазууга өтүү",
            "menu_empty": "(Бош)",
            "menu_exit": "Чыгуу",
            "ctx_delete": "Өчүрүү",
            "ctx_subtask": "Ички милдет кошуу",
            "ctx_cancel": "Жокко чыгаруу",
            "ctx_restore": "Калыбына келтирүү",
            "archive_title": "АРХИВДИ БАШКАРУУ",
            "btn_open": "Ачуу",
            "btn_delete": "Өчүрүү",
            "btn_close": "Жабуу",
            "hint_double_click": "Ачуу үчүн эки жолу басыңыз",
            "msg_del_title": "Өчүрүү",
            "msg_del_text": "Бул жазууну биротоло өчүрөсүзб?",
            "note_prefix": "Жазба уақыты:",
            "note_to": "-",
            "done_by": "аткарылды",
            "rename_title": "Атын өзгөртүү",
            "rename_label": "Жазуунун аты:"
        },
        "uz": {
            "title_default": "VAZIFALAR",
            "new_task_hint": "+ Yangi vazifa",
            "menu_new_note": "📝 Yangi qayd",
            "menu_rename": "✏️ Qayta nomlash",
            "menu_archive": "🗑 Arxiv",
            "menu_language": "🌐 Til",
            "menu_go_to": "🗂 Qaydga o'tish",
            "menu_empty": "(Bo'sh)",
            "menu_exit": "Chiqish",
            "ctx_delete": "O'chirish",
            "ctx_subtask": "Ichki vazifa qo'shish",
            "ctx_cancel": "Bekor qilish",
            "ctx_restore": "Tiklash",
            "archive_title": "ARXIV BOSHQARUVI",
            "btn_open": "Ochish",
            "btn_delete": "O'chirish",
            "btn_close": "Yopish",
            "hint_double_click": "Ochish uchun ikki marta bosing",
            "msg_del_title": "O'chirish",
            "msg_del_text": "Ushbu qaydni butunlay o'chirib tashlaysizmi?",
            "note_prefix": "Qayd vaqti:",
            "note_to": "-",
            "done_by": "bajarildi",
            "rename_title": "Qayta nomlash",
            "rename_label": "Qayd nomi:"
        },
        "tt": {
            "title_default": "БУРЫЧЛАР",
            "new_task_hint": "+ Яңа бурыч",
            "menu_new_note": "📝 Яңа язма",
            "menu_rename": "✏️ Исемен үзгәртү",
            "menu_archive": "🗑 Архив",
            "menu_language": "🌐 Тел",
            "menu_go_to": "🗂 Язмага күчү",
            "menu_empty": "(Буш)",
            "menu_exit": "Чыгу",
            "ctx_delete": "Бетерү",
            "ctx_subtask": "Өстәмә бурыч",
            "ctx_cancel": "Гамәлдән чыгару",
            "ctx_restore": "Торгызу",
            "archive_title": "АРХИВ ИДАРӘСЕ",
            "btn_open": "Ачу",
            "btn_delete": "Бетерү",
            "btn_close": "Ябу",
            "hint_double_click": "Ачу өчен ике тапкыр басыгыз",
            "msg_del_title": "Бетерү",
            "msg_del_text": "Бу язманы бөтенләй бетерергәме?",
            "note_prefix": "Язма вакыты:",
            "note_to": "-",
            "done_by": "үтәлде",
            "rename_title": "Исемен үзгәртү",
            "rename_label": "Язма исеме:"
        },
        "az": {
            "title_default": "TAPŞIRIQLAR",
            "new_task_hint": "+ Yeni tapşırıq",
            "menu_new_note": "📝 Yeni Qeyd",
            "menu_rename": "✏️ Adını dəyiş",
            "menu_archive": "🗑 Arxiv",
            "menu_language": "🌐 Dil",
            "menu_go_to": "🗂 Qeydə keç",
            "menu_empty": "(Boş)",
            "menu_exit": "Çıxış",
            "ctx_delete": "Sil",
            "ctx_subtask": "Alt tapşırıq əlavə et",
            "ctx_cancel": "Ləğv et",
            "ctx_restore": "Bərpa et",
            "archive_title": "ARXİV İDARƏETMƏSİ",
            "btn_open": "Aç",
            "btn_delete": "Sil",
            "btn_close": "Bağla",
            "hint_double_click": "Açmaq üçün iki dəfə klikləyin",
            "msg_del_title": "Sil",
            "msg_del_text": "Bu qeyd həmişəlik silinsin?",
            "note_prefix": "Qeyd tarixi:",
            "note_to": "-",
            "done_by": "bitdi",
            "rename_title": "Adını dəyiş",
            "rename_label": "Qeyd adı:"
        },
        "tr": {
            "title_default": "YAPILACAKLAR",
            "new_task_hint": "+ Yeni görev",
            "menu_new_note": "📝 Yeni Not",
            "menu_rename": "✏️ Yeniden Adlandır",
            "menu_archive": "🗑 Arşiv Yönetimi",
            "menu_language": "🌐 Dil",
            "menu_go_to": "🗂 Nota Git",
            "menu_empty": "(Boş)",
            "menu_exit": "Çıkış",
            "ctx_delete": "Sil",
            "ctx_subtask": "Alt görev ekle",
            "ctx_cancel": "İptal et / Atla",
            "ctx_restore": "Geri Yükle",
            "archive_title": "ARŞİV YÖNETİMİ",
            "btn_open": "Aç",
            "btn_delete": "Sil",
            "btn_close": "Kapat",
            "hint_double_click": "Açmak için çift tıkla",
            "msg_del_title": "Sil",
            "msg_del_text": "Bu not kalıcı olarak silinsin mi?",
            "note_prefix": "Not tarihi:",
            "note_to": "-",
            "done_by": "tamamlandı",
            "rename_title": "Yeniden Adlandır",
            "rename_label": "Not adı:"
        },
        "cs": {
            "title_default": "ÚKOLY",
            "new_task_hint": "+ Nový úkol",
            "menu_new_note": "📝 Nová poznámka",
            "menu_rename": "✏️ Přejmenovat",
            "menu_archive": "🗑 Archiv",
            "menu_language": "🌐 Jazyk",
            "menu_go_to": "🗂 Přejít na poznámku",
            "menu_empty": "(Prázdné)",
            "menu_exit": "Konec",
            "ctx_delete": "Smazat",
            "ctx_subtask": "Přidat podúkol",
            "ctx_cancel": "Zrušit / Přeskočit",
            "ctx_restore": "Obnovit",
            "archive_title": "SPRÁVA ARCHIVU",
            "btn_open": "Otevřít",
            "btn_delete": "Smazat",
            "btn_close": "Zavřít",
            "hint_double_click": "Dvojklikem otevřete",
            "msg_del_title": "Smazat",
            "msg_del_text": "Trvale smazat tuto poznámku?",
            "note_prefix": "Poznámka od",
            "note_to": "do",
            "done_by": "hotovo",
            "rename_title": "Přejmenovat",
            "rename_label": "Název poznámky:"
        },
        "uk": {
            "title_default": "ЗАВДАННЯ",
            "new_task_hint": "+ Нове завдання",
            "menu_new_note": "📝 Нова нотатка",
            "menu_rename": "✏️ Перейменувати",
            "menu_archive": "🗑 Архів",
            "menu_language": "🌐 Мова",
            "menu_go_to": "🗂 Перейти до нотатки",
            "menu_empty": "(Пусто)",
            "menu_exit": "Вихід",
            "ctx_delete": "Видалити",
            "ctx_subtask": "Додати підзавдання",
            "ctx_cancel": "Скасувати / Пропустити",
            "ctx_restore": "Відновити",
            "archive_title": "КЕРУВАННЯ АРХІВОМ",
            "btn_open": "Відкрити",
            "btn_delete": "Видалити",
            "btn_close": "Закрити",
            "hint_double_click": "Двічі клацніть, щоб відкрити",
            "msg_del_title": "Видалення",
            "msg_del_text": "Видалити цю нотатку назавжди?",
            "note_prefix": "Нотатка від",
            "note_to": "до",
            "done_by": "зроблено",
            "rename_title": "Перейменувати",
            "rename_label": "Назва нотатки:"
        },
        "pl": {
            "title_default": "ZADANIA",
            "new_task_hint": "+ Nowe zadanie",
            "menu_new_note": "📝 Nowa notatka",
            "menu_rename": "✏️ Zmień nazwę",
            "menu_archive": "🗑 Archiwum",
            "menu_language": "🌐 Język",
            "menu_go_to": "🗂 Przejdź do",
            "menu_empty": "(Puste)",
            "menu_exit": "Wyjście",
            "ctx_delete": "Usuń",
            "ctx_subtask": "Dodaj podzadanie",
            "ctx_cancel": "Anuluj / Pomiń",
            "ctx_restore": "Przywróć",
            "archive_title": "ZARZĄDZANIE ARCHIWUM",
            "btn_open": "Otwórz",
            "btn_delete": "Usuń",
            "btn_close": "Zamknij",
            "hint_double_click": "Kliknij dwukrotnie, aby otworzyć",
            "msg_del_title": "Usuwanie",
            "msg_del_text": "Trwale usunąć tę notatkę?",
            "note_prefix": "Notatka z",
            "note_to": "do",
            "done_by": "wykonano",
            "rename_title": "Zmień nazwę",
            "rename_label": "Nazwa notatki:"
        },
        "es": {
            "title_default": "TAREAS",
            "new_task_hint": "+ Nueva tarea",
            "menu_new_note": "📝 Nueva Nota",
            "menu_rename": "✏️ Renombrar",
            "menu_archive": "🗑 Archivo",
            "menu_language": "🌐 Idioma",
            "menu_go_to": "🗂 Ir a la nota",
            "menu_empty": "(Vacío)",
            "menu_exit": "Salir",
            "ctx_delete": "Eliminar",
            "ctx_subtask": "Añadir subtarea",
            "ctx_cancel": "Cancelar / Omitir",
            "ctx_restore": "Restaurar",
            "archive_title": "GESTIÓN DE ARCHIVOS",
            "btn_open": "Abrir",
            "btn_delete": "Eliminar",
            "btn_close": "Cerrar",
            "hint_double_click": "Doble clic para abrir",
            "msg_del_title": "Eliminar",
            "msg_del_text": "¿Eliminar esta nota permanentemente?",
            "note_prefix": "Nota de",
            "note_to": "a",
            "done_by": "hecho",
            "rename_title": "Renombrar",
            "rename_label": "Nombre de la nota:"
        },
        "fr": {
            "title_default": "TÂCHES",
            "new_task_hint": "+ Nouvelle tâche",
            "menu_new_note": "📝 Nouvelle note",
            "menu_rename": "✏️ Renommer",
            "menu_archive": "🗑 Archives",
            "menu_language": "🌐 Langue",
            "menu_go_to": "🗂 Aller à la note",
            "menu_empty": "(Vide)",
            "menu_exit": "Quitter",
            "ctx_delete": "Supprimer",
            "ctx_subtask": "Ajouter sous-tâche",
            "ctx_cancel": "Annuler / Sauter",
            "ctx_restore": "Rétablir",
            "archive_title": "GESTION DES ARCHIVES",
            "btn_open": "Ouvrir",
            "btn_delete": "Supprimer",
            "btn_close": "Fermer",
            "hint_double_click": "Double-cliquez pour ouvrir",
            "msg_del_title": "Supprimer",
            "msg_del_text": "Supprimer définitivement cette note ?",
            "note_prefix": "Note du",
            "note_to": "au",
            "done_by": "fait le",
            "rename_title": "Renommer",
            "rename_label": "Nom de la note :"
        },
        "de": {
            "title_default": "AUFGABEN",
            "new_task_hint": "+ Neue Aufgabe",
            "menu_new_note": "📝 Neue Notiz",
            "menu_rename": "✏️ Umbenennen",
            "menu_archive": "🗑 Archiv",
            "menu_language": "🌐 Sprache",
            "menu_go_to": "🗂 Zu Notiz wechseln",
            "menu_empty": "(Leer)",
            "menu_exit": "Beenden",
            "ctx_delete": "Löschen",
            "ctx_subtask": "Teilaufgabe hinzufügen",
            "ctx_cancel": "Abbrechen",
            "ctx_restore": "Wiederherstellen",
            "archive_title": "ARCHIVVERWALTUNG",
            "btn_open": "Öffnen",
            "btn_delete": "Löschen",
            "btn_close": "Schließen",
            "hint_double_click": "Doppelklick zum Öffnen",
            "msg_del_title": "Löschen",
            "msg_del_text": "Diese Notiz dauerhaft löschen?",
            "note_prefix": "Notiz vom",
            "note_to": "bis",
            "done_by": "erledigt",
            "rename_title": "Umbenennen",
            "rename_label": "Notizname:"
        },
        "nl": {
            "title_default": "TAKEN",
            "new_task_hint": "+ Nieuwe taak",
            "menu_new_note": "📝 Nieuwe notitie",
            "menu_rename": "✏️ Hernoemen",
            "menu_archive": "🗑 Archief",
            "menu_language": "🌐 Taal",
            "menu_go_to": "🗂 Ga naar notitie",
            "menu_empty": "(Leeg)",
            "menu_exit": "Afsluiten",
            "ctx_delete": "Verwijderen",
            "ctx_subtask": "Subtaak toevoegen",
            "ctx_cancel": "Annuleren",
            "ctx_restore": "Herstellen",
            "archive_title": "ARCHIEFBEHEER",
            "btn_open": "Openen",
            "btn_delete": "Verwijderen",
            "btn_close": "Sluiten",
            "hint_double_click": "Dubbelklik om te openen",
            "msg_del_title": "Verwijderen",
            "msg_del_text": "Deze notitie permanent verwijderen?",
            "note_prefix": "Notitie van",
            "note_to": "tot",
            "done_by": "klaar op",
            "rename_title": "Hernoemen",
            "rename_label": "Notitienaam:"
        },
        "it": {
            "title_default": "DA FARE",
            "new_task_hint": "+ Nuova attività",
            "menu_new_note": "📝 Nuova nota",
            "menu_rename": "✏️ Rinomina",
            "menu_archive": "🗑 Archivio",
            "menu_language": "🌐 Lingua",
            "menu_go_to": "🗂 Vai alla nota",
            "menu_empty": "(Vuoto)",
            "menu_exit": "Esci",
            "ctx_delete": "Elimina",
            "ctx_subtask": "Aggiungi sottoattività",
            "ctx_cancel": "Annulla",
            "ctx_restore": "Ripristina",
            "archive_title": "GESTIONE ARCHIVIO",
            "btn_open": "Apri",
            "btn_delete": "Elimina",
            "btn_close": "Chiudi",
            "hint_double_click": "Doppio clic per aprire",
            "msg_del_title": "Elimina",
            "msg_del_text": "Eliminare definitivamente questa nota?",
            "note_prefix": "Nota del",
            "note_to": "al",
            "done_by": "fatto il",
            "rename_title": "Rinomina",
            "rename_label": "Nome nota:"
        },
        "pt": {
            "title_default": "TAREFAS",
            "new_task_hint": "+ Nova tarefa",
            "menu_new_note": "📝 Nova Nota",
            "menu_rename": "✏️ Renomear",
            "menu_archive": "🗑 Arquivo",
            "menu_language": "🌐 Idioma",
            "menu_go_to": "🗂 Ir para nota",
            "menu_empty": "(Vazio)",
            "menu_exit": "Sair",
            "ctx_delete": "Excluir",
            "ctx_subtask": "Adicionar subtarefa",
            "ctx_cancel": "Cancelar",
            "ctx_restore": "Restaurar",
            "archive_title": "GERENCIAR ARQUIVO",
            "btn_open": "Abrir",
            "btn_delete": "Excluir",
            "btn_close": "Fechar",
            "hint_double_click": "Duplo clique para abrir",
            "msg_del_title": "Excluir",
            "msg_del_text": "Excluir esta nota permanentemente?",
            "note_prefix": "Nota de",
            "note_to": "até",
            "done_by": "feito em",
            "rename_title": "Renomear",
            "rename_label": "Nome da nota:"
        },
        "ko": {
            "title_default": "할 일",
            "new_task_hint": "+ 새 작업",
            "menu_new_note": "📝 새 메모",
            "menu_rename": "✏️ 이름 변경",
            "menu_archive": "🗑 아카이브",
            "menu_language": "🌐 언어",
            "menu_go_to": "🗂 메모로 이동",
            "menu_empty": "(비어 있음)",
            "menu_exit": "종료",
            "ctx_delete": "삭제",
            "ctx_subtask": "하위 작업 추가",
            "ctx_cancel": "취소",
            "ctx_restore": "복원",
            "archive_title": "아카이브 관리",
            "btn_open": "열기",
            "btn_delete": "삭제",
            "btn_close": "닫기",
            "hint_double_click": "더블 클릭하여 열기",
            "msg_del_title": "삭제",
            "msg_del_text": "이 메모를 영구적으로 삭제하시겠습니까?",
            "note_prefix": "작성일:",
            "note_to": "~",
            "done_by": "완료:",
            "rename_title": "이름 변경",
            "rename_label": "메모 이름:"
        },
        "ja": {
            "title_default": "タスク",
            "new_task_hint": "+ 新しいタスク",
            "menu_new_note": "📝 新規メモ",
            "menu_rename": "✏️ 名前の変更",
            "menu_archive": "🗑 アーカイブ",
            "menu_language": "🌐 言語",
            "menu_go_to": "🗂 メモへ移動",
            "menu_empty": "(空)",
            "menu_exit": "終了",
            "ctx_delete": "削除",
            "ctx_subtask": "サブタスクを追加",
            "ctx_cancel": "キャンセル",
            "ctx_restore": "復元",
            "archive_title": "アーカイブ管理",
            "btn_open": "開く",
            "btn_delete": "削除",
            "btn_close": "閉じる",
            "hint_double_click": "ダブルクリックで開く",
            "msg_del_title": "削除",
            "msg_del_text": "このメモを完全に削除しますか？",
            "note_prefix": "メモ作成日:",
            "note_to": "完了日:",
            "done_by": "完了:",
            "rename_title": "名前の変更",
            "rename_label": "メモの名前:"
        },
        "zh": {
            "title_default": "待办事项",
            "new_task_hint": "+ 新任务",
            "menu_new_note": "📝 新建笔记",
            "menu_rename": "✏️ 重命名",
            "menu_archive": "🗑 归档管理",
            "menu_language": "🌐 语言",
            "menu_go_to": "🗂 跳转到笔记",
            "menu_empty": "(空)",
            "menu_exit": "退出",
            "ctx_delete": "删除",
            "ctx_subtask": "添加子任务",
            "ctx_cancel": "取消",
            "ctx_restore": "恢复",
            "archive_title": "归档管理",
            "btn_open": "打开",
            "btn_delete": "删除",
            "btn_close": "关闭",
            "hint_double_click": "双击打开",
            "msg_del_title": "删除",
            "msg_del_text": "永久删除此笔记？",
            "note_prefix": "笔记于",
            "note_to": "至",
            "done_by": "完成于",
            "rename_title": "重命名",
            "rename_label": "笔记名称:"
        },
        "ar": {
            "title_default": "المهام",
            "new_task_hint": "+ مهمة جديدة",
            "menu_new_note": "📝 ملاحظة جديدة",
            "menu_rename": "✏️ إعادة تسمية",
            "menu_archive": "🗑 الأرشيف",
            "menu_language": "🌐 اللغة",
            "menu_go_to": "🗂 الذهاب إلى الملاحظة",
            "menu_empty": "(فارغ)",
            "menu_exit": "خروج",
            "ctx_delete": "حذف",
            "ctx_subtask": "إضافة مهمة فرعية",
            "ctx_cancel": "إلغاء",
            "ctx_restore": "استعادة",
            "archive_title": "إدارة الأرشيف",
            "btn_open": "فتح",
            "btn_delete": "حذف",
            "btn_close": "إغلاق",
            "hint_double_click": "انقر مرتين للفتح",
            "msg_del_title": "حذف",
            "msg_del_text": "هل تريد حذف هذه الملاحظة نهائيًا؟",
            "note_prefix": "ملاحظة من",
            "note_to": "إلى",
            "done_by": "أنجزت في",
            "rename_title": "إعادة تسمية",
            "rename_label": "اسم الملاحظة:"
        }
    }

    # ИСПРАВЛЕННЫЙ МЕТОД: теперь принимает default=None
    @staticmethod
    def t(key, default=None):
        # Берем словарь для текущего языка, если нет - английский
        lang_dict = Loc.data.get(Loc.lang, Loc.data["en"])
        # Берем значение по ключу, если нет - возвращаем default, если default нет - сам ключ
        return lang_dict.get(key, default if default is not None else key)